### PR TITLE
Parse improvements

### PR DESCRIPTION
**Pull request by rarylson**
Some parsing improvements. These improvements fixes some known issues ( #5, #7, #9, #10, #11). They are:

- Using stronger header regexp to avoid wrongly matching header
- Fix ASN parsing for hops with multiple ASNs
- Parse outputs with only IPs (`traceroute -n`)
- Fix timeout probes can have name/ip or not depending of the position in traceroute output
- Fix confusion between `rtt = 0` (very low rtt) and `rtt = None` (timeout)
- And other minor things

### CODE REVIEW

**Comment by rarylson** [comment]
Side notes:

1) Additional discussion are in issue #10: I don't know if my current solution to the issue is the best one.

2) You said in `README.md` that header can be in other lines than the first one (you says that it generally is in the first two lines - so it can be in other lines too). If it is true, maybe I commit I proposed breaks things. In this case, you can give me and example and I will try fix my code to include these cases.

**Update**: The only test case the traceroute header was not in the first line was when a forced an error using the `-A` flag. So if you decide do NOT support this flag, you can hardcode the header parsing to the first output line. The advantage is that the header line can be printed together in the ParseError exception (as I did in the pull request code). Otherwise, a more generic exception (with a generic message like "header was not found") should be used in the exception.

```console
$ traceroute -A 10.10.10.1 vialink.com.br
traceroute: connect: Connection refused
traceroute: as_setup failed, AS# lookups disabled
traceroute to vialink.com.br (52.33.65.153), 64 hops max, 52 byte packets
 1  192.168.0.1 (192.168.0.1)  1.772 ms  0.765 ms  1.280 ms
[...]
```

3) **Update:** If you choose the merge pull #8, including some improvements I propose in that pull, I can rebase my pull request (#12, this one) on top of #8, solving merge conflicts between the two pull requests.

4) You do not provide test cases. I used some test cases when testing the code in the pull request. I'm attach them here. I run them with `python test.py TEST_CASE`.

[asn_multi.txt](https://github.com/lbenitez000/trparse/files/1776696/asn_multi.txt)
[asn.txt](https://github.com/lbenitez000/trparse/files/1776697/asn.txt)
[header.txt](https://github.com/lbenitez000/trparse/files/1776698/header.txt)
[multi.txt](https://github.com/lbenitez000/trparse/files/1776699/multi.txt)
[only_ips.txt](https://github.com/lbenitez000/trparse/files/1776700/only_ips.txt)
[with_partial_timeouts.txt](https://github.com/lbenitez000/trparse/files/1776701/with_partial_timeouts.txt)
[without_header.txt](https://github.com/lbenitez000/trparse/files/1776702/without_header.txt)

5) You parser is not a strict parser (wrong outputs can be parsed). There is no guarantee that invalid outputs will raise `ParseError` exceptions. However, good outputs will produce a correct parsed object (ASN) in most cases. Your parser is a best effort parser.

If you want to implement a strict parser, grammar/state-machine algorithms are better. I started to implement some code (based on the state-machine concept) [in this commit, in a different branch](https://github.com/rarylson/trparse/commit/e567561b3f235ed8d1cea43db6ee058ed0abd2c9). It is NOT a good code and it is still not a strict parser (this is why I do not include it in the pull request). But it may help you to understand the general idea.

Here, it's a link with a list of libs that may help to create strict parsers: https://wiki.python.org/moin/LanguageParsing.

**Comment by magebarf** [comment]
Hey @rarylson I think I found one of the cases where header is not actually in first line, but I'm not sure whether this is fully standard across different OSes or not.

My use case is `traceroute targethost > logfile 2>&1`, running on macOS. At least on macOS the whole header isn't part of stdout, it's part of stderr, which means I need both of them written to file to have the original header to start with.

The case I've seen is for hosts where there're multiple dns entries, in which case a warning is given to indicate this, as well as point out which of the entries is being used explicitly. My leading two rows from such a host (t.co) looks like:

`traceroute: Warning: t.co has multiple addresses; using 199.16.156.75
traceroute to t.co (199.16.156.75), 64 hops max, 52 byte packets`

**Comment by rarylson** [comment]
Hi Patrik @magebarf,

Thanks for pointing this.

I'll fix this soon.

**Comment by rarylson** [comment]
I see that:

- The project improved a lot in v0.3.0
- Some of the commits proposed here in this PR just do not apply anymore (they are already fixed on v0.3.0)

So, I'm cancelling this PR.

I'll create new PRs, but smaller, addressing the remaining bugs and improvements that I'm proposing.

Also, creating smaller PRs will allow the project owner to just choose the ones that makes more sense.

**Pull request closed without merging**
