### PR TITLE
Making usable for python 2 and python 3

### PR DESCRIPTION
**Pull request by gleichda**
fixing issue #6 for Python 3 following solution provided by sam1902

### CODE REVIEW

**Comment by rarylson** [comment]
Hi @mirgleich. I'm not the project owner, but I'm trying to fix some things and make some contribution to the project (just like you).

I realized that you already made changes needed for `trparse.py` can be used in Python3.

But the `test.py` file still using specific Python2 syntax. Would you mind to update `test.py` so the whole project will be Python3 compatible? I think only the print statements should be updated. The following patch seems to solve the problem:

```
diff --git a/test.py b/test.py
index c8912df..dca9a20 100644
--- a/test.py
+++ b/test.py
@@ -1,5 +1,7 @@
 #!/usr/bin/python

+from __future__ import print_function
+
 import sys
 import glob
 import trparse
@@ -7,7 +9,7 @@ import trparse
 def main():

     if len(sys.argv) == 1:
-        print "Missing test files"
+        print("Missing test files")
         sys.exit(1)

     for file_pattern in sys.argv[1:]:
@@ -17,11 +19,11 @@ def main():
         for filename in filenames:
             with open(filename, 'r') as f:

-                print "Loading {}".format(filename)
+                print("Loading {}".format(filename))
                 tr = trparse.load(f)

-                print "Dumping"
-                print tr
+                print("Dumping")
+                print(tr)

 if __name__ == "__main__":
     main()
```

If this do not bore you, you could also update the `classifiers` in `setup.py` adding the Python3 versions you have tested (I have only tested Python 3.5 - if seems to work well after applying your fix). For example, to add only Python 3.5, the diff would be:

```
diff --git a/setup.py b/setup.py
index fa4a3fe..0dd3f61 100644
--- a/setup.py
+++ b/setup.py
@@ -26,10 +26,11 @@ classifiers = [
     "Operating System :: POSIX :: Linux",
     "Operating System :: Unix",
     "Programming Language :: Python",
-    "Programming Language :: Python :: 2 :: Only",
     "Programming Language :: Python :: 2",
     "Programming Language :: Python :: 2.6",
     "Programming Language :: Python :: 2.7",
+    "Programming Language :: Python :: 3",
+    "Programming Language :: Python :: 3.5",
     "Topic :: Internet",
     "Topic :: Internet :: Log Analysis",
     "Topic :: Internet :: Name Service (DNS)",
@@ -48,4 +49,4 @@ setup(name='trparse',
       license='MIT License',
       py_modules=['trparse'],
       classifiers=classifiers
-)
\ No newline at end of file
+)
```

**Comment by gleichda** [comment]
@rarylson could you just open a pullrequest to my project then i will merge it and place another pull request to this?

**Comment by rarylson** [comment]
Hi @mirgleich. I already did a pull request in your fork: https://github.com/mirgleich/trparse/pull/1.

If you merge it in your master branch, your current pull request (#8, this one) will refer to the new HEAD in your master branch. So no new pull request need to be created. :)

**Comment by gleichda** [comment]
merged now
Thanks for that info.
Did not know that so far ;)
just waiting for @lbenitez000 to merge that into master

**Comment by gleichda** [comment]
Closing now as there is no progress

**Pull request closed without merging**
